title: Burak Tutkavul — CS-499 ePortfolio
description: Cybersecurity-focused capstone portfolio
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Keep the header clean and ordered
header_pages:
  - self-assessment.md
  - artifacts.md         # new hub page
  - code-review.md
